openapi: 3.0.3
info:
  title: Authentication System API
  version: 1.0.0
  description: |
    Authentication API powered by better-auth with custom extensions.

    **Features**:
    - Email/password authentication
    - OAuth (Google, GitHub)
    - Account linking (auto-link same email)
    - Email verification (non-blocking)
    - Password reset
    - Role-based access control
    - Security event logging

servers:
  - url: http://localhost:3000/api/auth
    description: Local development
  - url: https://yourdomain.com/api/auth
    description: Production

tags:
  - name: Authentication
    description: Login, signup, and logout operations
  - name: OAuth
    description: Social provider authentication
  - name: Account
    description: User profile and account management
  - name: Security
    description: Security events and audit logging
  - name: Admin
    description: Administrative operations (requires admin role)

paths:
  # ============================================================================
  # Authentication Endpoints
  # ============================================================================

  /sign-up/email:
    post:
      tags: [Authentication]
      summary: Sign up with email and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 12
                  description: Must be 12+ chars with uppercase, lowercase, number, special char
                name:
                  type: string
                  maxLength: 100
                callbackURL:
                  type: string
                  format: uri
      responses:
        '200':
          description: Account created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '429':
          $ref: '#/components/responses/RateLimited'

  /sign-in/email:
    post:
      tags: [Authentication]
      summary: Sign in with email and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                callbackURL:
                  type: string
                  format: uri
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          $ref: '#/components/responses/RateLimited'

  /sign-out:
    post:
      tags: [Authentication]
      summary: Sign out current session
      security:
        - cookieAuth: []
      responses:
        '200':
          description: Logout successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean

  # ============================================================================
  # OAuth Endpoints
  # ============================================================================

  /sign-in/social:
    post:
      tags: [OAuth]
      summary: Sign in with OAuth provider (Google, GitHub)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [provider]
              properties:
                provider:
                  type: string
                  enum: [google, github]
                callbackURL:
                  type: string
                  format: uri
      responses:
        '302':
          description: Redirect to OAuth provider
        '400':
          $ref: '#/components/responses/BadRequest'

  /callback/{provider}:
    get:
      tags: [OAuth]
      summary: OAuth callback endpoint
      parameters:
        - name: provider
          in: path
          required: true
          schema:
            type: string
            enum: [google, github]
        - name: code
          in: query
          required: true
          schema:
            type: string
        - name: state
          in: query
          schema:
            type: string
      responses:
        '302':
          description: Redirect to application after successful auth
        '400':
          $ref: '#/components/responses/BadRequest'

  /link-social:
    post:
      tags: [OAuth]
      summary: Link OAuth provider to existing account
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [provider]
              properties:
                provider:
                  type: string
                  enum: [google, github]
      responses:
        '200':
          description: OAuth account linked successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '409':
          description: Provider already linked to another account

  # ============================================================================
  # Account Management Endpoints
  # ============================================================================

  /get-session:
    get:
      tags: [Account]
      summary: Get current user session
      security:
        - cookieAuth: []
      responses:
        '200':
          description: Session retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /update-user:
    post:
      tags: [Account]
      summary: Update user profile
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  minLength: 1
                  maxLength: 100
                email:
                  type: string
                  format: email
                image:
                  type: string
                  format: uri
      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '409':
          description: Email already in use

  /change-password:
    post:
      tags: [Account]
      summary: Change user password
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [currentPassword, newPassword]
              properties:
                currentPassword:
                  type: string
                newPassword:
                  type: string
                  minLength: 12
      responses:
        '200':
          description: Password changed successfully
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          description: Current password incorrect

  /verify-email:
    post:
      tags: [Account]
      summary: Verify email address
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [token]
              properties:
                token:
                  type: string
      responses:
        '200':
          description: Email verified successfully
        '400':
          description: Invalid or expired token

  /send-verification-email:
    post:
      tags: [Account]
      summary: Resend verification email
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email]
              properties:
                email:
                  type: string
                  format: email
                callbackURL:
                  type: string
                  format: uri
      responses:
        '200':
          description: Verification email sent
        '429':
          $ref: '#/components/responses/RateLimited'

  /forget-password:
    post:
      tags: [Account]
      summary: Request password reset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email]
              properties:
                email:
                  type: string
                  format: email
                callbackURL:
                  type: string
                  format: uri
      responses:
        '200':
          description: Password reset email sent
        '429':
          $ref: '#/components/responses/RateLimited'

  /reset-password:
    post:
      tags: [Account]
      summary: Reset password with token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [token, newPassword]
              properties:
                token:
                  type: string
                newPassword:
                  type: string
                  minLength: 12
      responses:
        '200':
          description: Password reset successfully
        '400':
          description: Invalid or expired token

  # ============================================================================
  # Security Endpoints (Custom)
  # ============================================================================

  /security-events:
    get:
      tags: [Security]
      summary: Get security audit log
      security:
        - cookieAuth: []
      parameters:
        - name: userId
          in: query
          schema:
            type: string
        - name: eventType
          in: query
          schema:
            type: string
            enum: [authentication, account_management, security, admin_actions]
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 50
        - name: offset
          in: query
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        '200':
          description: Security events retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SecurityEventsResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: Insufficient permissions (admin only)

  # ============================================================================
  # Admin Endpoints
  # ============================================================================

  /admin/set-role:
    post:
      tags: [Admin]
      summary: Set user role (admin only)
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [userId, role]
              properties:
                userId:
                  type: string
                role:
                  type: string
                  enum: [admin, moderator, user]
      responses:
        '200':
          description: Role updated successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: Insufficient permissions

  /admin/ban-user:
    post:
      tags: [Admin]
      summary: Ban user (admin only)
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [userId, reason]
              properties:
                userId:
                  type: string
                reason:
                  type: string
                  maxLength: 500
                expiresAt:
                  type: string
                  format: date-time
      responses:
        '200':
          description: User banned successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: Insufficient permissions

  /admin/unban-user:
    post:
      tags: [Admin]
      summary: Unban user (admin only)
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [userId]
              properties:
                userId:
                  type: string
      responses:
        '200':
          description: User unbanned successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: Insufficient permissions

# ============================================================================
# Components
# ============================================================================

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: better-auth.session_token

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
          nullable: true
        email:
          type: string
          format: email
        emailVerified:
          type: boolean
        image:
          type: string
          format: uri
          nullable: true
        role:
          type: string
          enum: [admin, moderator, user]
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Session:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        token:
          type: string
        expiresAt:
          type: string
          format: date-time
        ipAddress:
          type: string
          nullable: true
        userAgent:
          type: string
          nullable: true
        createdAt:
          type: string
          format: date-time

    SessionResponse:
      type: object
      properties:
        session:
          $ref: '#/components/schemas/Session'
        user:
          $ref: '#/components/schemas/User'

    SecurityEvent:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
          nullable: true
        eventType:
          type: string
          enum: [authentication, account_management, security, admin_actions]
        action:
          type: string
        ipAddress:
          type: string
        userAgent:
          type: string
          nullable: true
        success:
          type: boolean
        metadata:
          type: object
          additionalProperties: true
          nullable: true
        createdAt:
          type: string
          format: date-time

    SecurityEventsResponse:
      type: object
      properties:
        events:
          type: array
          items:
            $ref: '#/components/schemas/SecurityEvent'
        total:
          type: integer
        hasMore:
          type: boolean

    Error:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
            details:
              type: object
              additionalProperties: true

    RateLimitError:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
              enum: [RATE_LIMIT_EXCEEDED]
            message:
              type: string
            retryAfter:
              type: integer
              description: Seconds until next request allowed

  responses:
    BadRequest:
      description: Invalid request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    Unauthorized:
      description: Not authenticated
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    RateLimited:
      description: Rate limit exceeded
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RateLimitError'
